# Completar todos los datos entre < >
version: "3.7"
services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    dns:
      - <172.20.0.2>
    networks:
      pihole:
        ipv4_address: <172.20.0.5>
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - <~/config/nginx/nginx.conf>:/etc/nginx/nginx.conf
      - <~/config/nginx/conf.d>:/etc/nginx/conf.d
      - <~/config/letsencrypt/etc/letsencrypt>:/etc/letsencrypt

networks:
  base:
    name: pihole
    external: true
